[package]
name = "tranet"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
geo-types = "0.7.12"
serde-pickle = "1.1.1"
utm = "0.1.6"
wkt = "0.10.3"
